import jsPDF from "jspdf";

interface ExportData {
  question: string;
  sql: string;
  results: any[];
  insights?: string;
}

export const exportEnterprisePDF = (
  data: ExportData,
  filename = "voicequery-report.pdf"
) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // ===== HEADER =====
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("VoiceQuery AI Report", pageWidth / 2, y, { align: "center" });

  y += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, y, {
    align: "center",
  });

  y += 15;

  // ===== QUESTION =====
  doc.setFont("helvetica", "bold");
  doc.text("User Question:", 10, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.text(doc.splitTextToSize(data.question || "-", 180), 10, y);
  y += 15;

  // ===== SQL =====
  doc.setFont("helvetica", "bold");
  doc.text("Generated SQL:", 10, y);
  y += 7;

  doc.setFont("courier", "normal");
  const sqlLines = doc.splitTextToSize(data.sql || "-", 180);
  doc.text(sqlLines, 10, y);
  y += sqlLines.length * 5 + 10;

  // ===== INSIGHTS =====
  if (data.insights) {
    doc.setFont("helvetica", "bold");
    doc.text("AI Insights:", 10, y);
    y += 7;

    doc.setFont("helvetica", "normal");
    const insightLines = doc.splitTextToSize(data.insights, 180);
    doc.text(insightLines, 10, y);
    y += insightLines.length * 5 + 10;
  }

  // ===== TABLE =====
  doc.setFont("helvetica", "bold");
  doc.text("Results Preview:", 10, y);
  y += 7;

  doc.setFont("helvetica", "normal");

  if (data.results.length > 0) {
    const keys = Object.keys(data.results[0]);

    // Table header
    doc.setFont("helvetica", "bold");
    doc.text(keys.join(" | "), 10, y);
    y += 7;

    doc.setFont("helvetica", "normal");

    // Rows (limit for readability)
    data.results.slice(0, 15).forEach((row) => {
      const rowText = keys.map((k) => String(row[k])).join(" | ");
      const lines = doc.splitTextToSize(rowText, 180);

      doc.text(lines, 10, y);
      y += lines.length * 5;

      if (y > 270) {
        doc.addPage();
        y = 15;
      }
    });
  }

  // ===== FOOTER =====
  doc.setFontSize(9);
  doc.text(
    "Generated by VoiceQuery AI • Confidential Report",
    pageWidth / 2,
    290,
    { align: "center" }
  );

  doc.save(filename);
};